### ISSUE TITLE
Nouvelle version du site ensap

### ISSUE THREAD

**Issue by FliiFe** [konnectors/ensap#241]
Salut!

L'ensap a fait peau neuve récemment et le connecteur (la version hébergée par Cozy) ne récupère plus les fiches de paies (ma fiche de paie de décembre apparaît bien sur le site mais le connecteur refuse de la prendre en compte).

Il y a un commit récent, je sais pas trop si c'est lié à ça ou pas. Si besoin, je peux jeter un oeil.

**Comment by riton** [comment]
Bonjour,

Cela peut-être lié à ce que j'ai rencontré dans https://github.com/riton/ensap-cli/issues/1.

Il semblerait qu'il soit désormais nécessaire de spécifier un `Accept: application/json` dans la requête. Le endpoint d'authentification redirige désormais sur la page d'accueil du site.

**Comment by isaring** [comment]
En clonant le dépôt et en testant en local (`yarn standalone`), apparaît une erreur liée à `cozyClient.new.models` (ligne 14).

Si l'on commente / supprime les lignes 14,15 et 109 du fichier `src/index.js` qui font référence à **Qualification**, le téléchargement des documents s'effectue normalement.

Je ne sais pas trop à quoi sert cette variable **qualification**, peut-être que @LucsT pourrait nous renseigner ? 

Dans tous les cas, @KillianCourvoisier a aussi proposé des modifications il y a quelques jours, à voir si cela débouchera sur une nouvelle _release_.

**Comment by isaring** [comment]
Semble résolu avec la version [1.5.0](https://github.com/konnectors/ensap/releases/tag/1.5.0).
